export const defaultOwnerPermissions = {
  dashboard: ["view", "edit"],
  appointments: ["view", "create", "edit"],
  branches: ["view", "create", "edit", "delete"],
  services: ["view", "create", "edit", "delete"],
  staff: ["view", "create", "edit", "delete"],
  staffSchedule: ["view", "create", "edit"],
  customers: ["view", "create", "edit"],
  pos: ["view", "create"],
  invoices: ["view", "create", "edit"],
  payments: ["view", "create", "edit"],
  inventory: ["view", "create", "edit", "delete"],
  purchases: ["view", "create", "edit"],
  memberships: ["view", "create", "edit"],
  packages: ["view", "create", "edit"],
  reports: ["view"],
  catalog: ["view", "create", "edit", "delete"],
  catalogAnalytics: ["view"],
  ecommerce: ["view", "create", "edit", "delete"],
  orders: ["view", "create", "edit", "delete"],
  campaigns: ["view", "create", "edit", "delete"],
  campaignTemplates: ["view", "create", "edit", "delete"],
  campaignAnalytics: ["view"],
  messageTemplates: ["view", "create", "edit"],
  loyalty: ["view", "create", "edit"],
  couponsGiftCards: ["view", "create", "edit", "delete"],
  feedback: ["view", "create", "edit"],
  enquiries: ["view", "create", "edit", "delete"],
  expenses: ["view", "create", "edit", "delete", "approve"],
  attendance: ["view", "create", "edit"],
  leaves: ["view", "create", "edit", "approve"],
  payroll: ["view", "create", "edit", "approve", "pay"],
  incentives: ["view", "create", "edit"],
  whatsapp: ["view", "create", "edit"],
  notifications: ["view", "create", "edit"],
  auditLogs: ["view"],
  customerPortalSettings: ["view", "edit"],
  settings: ["view", "edit"],
  support: ["view", "create"],
  advancedReports: ["view"],
  myDashboard: ["view"],
  myAppointments: ["view", "edit"],
  mySchedule: ["view"],
  myCommission: ["view"],
  myProfile: ["view", "edit"],
  myAttendance: ["view", "create", "edit"],
  myLeaves: ["view", "create"],
  myPayroll: ["view"],
  myPerformance: ["view"]
};
